---
# handlers file for ubuntu

- name: check or build ubuntu image
  docker_image: 
    path: "{{ubuntu_dir}}"
    name: "polymont/ubuntu"
    state: build
  tags: [ubuntu]
  notify: 
  - check or build java image

