# tasks file for docker / centos

- name: uninstall old docker on centos
  yum: 
    name: docker
    state: absent
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [docker]

- name: add docker repo on centos
  copy:
    src: centos_docker.repo
    dest: /etc/yum.repos.d/docker.repo
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [docker]

- name: install docker on centos
  yum: 
    name: "{{item}}"
    state: latest
  with_items:
  - docker-selinux
  - docker-engine
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [docker]

- name: install python-pip
  yum:
    name: python-pip
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [docker]

