# tasks file for docker / debian

- name: uninstall old docker on debian
  apt: 
    name: docker.io
    state: absent
  when: ansible_distribution == "Debian" and
          (ansible_distribution_release == "jessie" or ansible_distribution_release == "wheezy")
  tags: [docker]


- name: add repo key for debian
  apt_key: 
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  when: ansible_distribution == "Debian" and
          (ansible_distribution_release == "jessie" or ansible_distribution_release == "wheezy")
  tags: [docker]

- name: add repo for debian
  apt_repository: 
    repo: "{{item}}"
    state: present
  with_items:
  - "deb http://http.debian.net/debian {{ansible_distribution_release}}-backports main"
  - "deb https://apt.dockerproject.org/repo debian-{{ansible_distribution_release}} main"
  when: ansible_distribution == "Debian" and
          (ansible_distribution_release == "jessie" or ansible_distribution_release == "wheezy")
  tags: [docker]

- name: install docker and python-pip on debian
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - docker-engine
  - python-pip
  when: ansible_distribution == "Debian" and
          (ansible_distribution_release == "jessie" or ansible_distribution_release == "wheezy")
  tags: [docker]

- name: install python-pip on debian
  apt:
    name: python-pip
    state: present
  when: ansible_distribution == "Debian" and
          (ansible_distribution_release == "jessie" or ansible_distribution_release == "wheezy")
  tags: [docker]

