# tasks file for install / centos
# if system is old, we need to update all yum packages
- name: update yum
  yum: 
    name: "*"
    state: latest
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [install, update_all]

- name: Install EPEL repo
  yum: 
    name: "{{ epel_repo_url }}"
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [docker]

- name: Import EPEL GPG key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [docker]

- name: install yum sshpass openssh-clients
  yum: 
    name: "{{item}}"
    state: latest
  with_items:
    - sshpass
    - openssh-clients
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [install]

- name: open ssh port in centos 7 firewall
  firewalld:
    zone: public
    permanent: true
    immediate: true 
    state: enabled
    port: "{{item}}/tcp"
  with_items:
  - "{{remote_ssh_port}}"
  - "{{ansible_container_ssh_port}}"
  - "{{jenkins_ssh_port}}"
  - "{{gitblit_ssh_port}}"
  - "{{registry_ssh_port}}"
  - "{{nginx_ssh_port}}"
  - "{{gitblit_port}}"
  - "{{git_port}}"
  - "443"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [install]

