---

# Copy the configuration files in local
- hosts: platform

  tasks: 

  - name: create the local directory 
    local_action: file path={{config_path}} state=directory

  - name: pull the application directory for ansible container
    synchronize: mode=pull src={{project_home_dir}}/src/config/{{env}}/ dest={{config_path}}

# Read the existing deployment file and the old server if needed
- hosts: docker

  roles:
  - {role: deployment}

# Remove old containers on previous server
- hosts: server

  tasks:
  
  - name: include deployment file
    include_vars: "/opt/deployment/{{application}}-{{env}}.yml"

  - name: stop old containers
    command: docker stop {{item}} && docker rm {{item}}
    with_items: "{{containers}}"

  - name: remove old containers
    command: docker rm {{item}}
    with_items: "{{containers}}"

# Register the deployment file
- hosts: docker

  roles:
  - {role: register}
