
- hosts: platform

  tasks: 

  - name: create the local directory 
    local_action: file path={{config_path}} state=directory

  - name: pull the application directory for ansible container
    synchronize: mode=pull src={{project_home_dir}}/src/config/{{env}}/ dest={{config_path}}