
- hosts: docker-machines
  tasks:
  - debug: var="{{application}}_{{env}}"

  - name: create the local directory 
    local_action: file path={{ansible_application_dir}} state=directory

  - name: pull the application directory for ansible container
    synchronize: mode=pull src=/opt/data/jenkins_home/workspace/{{application}} dest={{ansible_application_dir}}