# execute: ansible-playbook mysql.yml -i inventory -e application=(applicationName) -e env=(environmentName)
# This playbook handles Tomcat component setup and deployment.

# Create and configure the container for Mysql Component
- hosts: docker-machines
  # load configuration for the component
  vars_files: 
    - "{{config_var_file}}"
  roles:
    - {role: common}
    - {role: mysql}
