# execute: ansible-playbook tomcat.yml -i inventory -e application=(applicationName) -e env=(environmentName)
# This playbook handles Tomcat component setup and deployment.

- hosts: platform
  # load configuration for the component
  vars_files: 
    - "{{config_var_file}}"
  # Gather artifacts to deploy
  roles:  
   - {role: artifact}
     
# Create the container for Tomcat Component. Prepare some files and configuration
- hosts: docker
  # load configuration for the component
  vars_files: 
    - "{{config_var_file}}"
  roles:
    - {role: common}
    - {role: tomcat}

# Prepare a 'tomcat' entry in inventory, pointing to the Tomcat container  
- hosts: docker
  # load configuration for the component
  vars_files: 
    - "{{config_var_file}}"
  tasks:
  # create a new "tomcat" node in the hosts inventory
  - name: add Tomcat container to inventory
    add_host: hostname="{{inventory_hostname}}"
        groups=tomcat
        ansible_ssh_user="sshuser"
        ansible_ssh_port="{{ports.ssh.host}}"

# Deploy in the Tomcat container
- hosts: tomcat
  # load configuration for the component
  vars_files: 
    - "{{config_var_file}}"
  # deploy in container
  roles:
    - {role: tomcat_application_deployer}
