# execute: ansible-playbook tomcat.yml -i inventory -e application=(applicationName) -e env=(environmentName)
- hosts: docker-machines
  roles:
    - {role: tomcat}
    
- hosts: docker-machines
  tasks:
  # create a new "tomcat" node in the hosts inventory, add Tomcat container to it in order to inject the war file
  - name: add Tomcat container to inventory
    add_host: hostname="{{inventory_hostname}}"
        groups=tomcat
        ansible_ssh_user="sshuser"
        ansible_ssh_port="{{tomcat.ports.ssh.host}}"
    
- hosts: tomcat
  roles:
    - {role: tomcat_application_deployer}
