# tasks file for docker / centos

- name: remove EPEL repo
  yum: 
    name: "{{ epel_repo_url }}"
    state: absent
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [docker]

- name: remove EPEL GPG key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: absent
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [docker]

- name: remove python-pip
  yum:
    name: python-pip
    state: absent
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [docker]

- name: remove docker on centos
  yum: 
    name: "{{item}}"
    state: absent
  with_items:
  - docker-engine
  - docker-selinux
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [docker]

- name: remove docker repo on centos
  file:
    path: /etc/yum.repos.d/docker.repo
    state: absent
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [docker]
