# tasks file for docker / debian

- name: remove backports
  apt_repository: 
    repo: "deb http://http.debian.net/debian {{ansible_distribution_release}}-backports main"
    state: absent
  when: ansible_distribution == "Debian" and
          (ansible_distribution_release == "jessie" or ansible_distribution_release == "wheezy")
  tags: [docker]

- name: remove docker on debian
  apt: 
    name: docker.io
    state: absent
  when: ansible_distribution == "Debian" and
          (ansible_distribution_release == "jessie" or ansible_distribution_release == "wheezy")
  tags: [docker]

- name: remove pip on debian
  easy_install: 
    name: pip
    state: absent
  when: ansible_distribution == "Debian" and
          (ansible_distribution_release == "jessie" or ansible_distribution_release == "wheezy")
  tags: [docker]

- name: remove  python-pip on debian
  apt:
    name: python-pip
    state: absent
  when: ansible_distribution == "Debian" and
          (ansible_distribution_release == "jessie" or ansible_distribution_release == "wheezy")
  tags: [docker]

