# tasks file for reset / debian

- name: remove repo for debian
  apt_repository: 
    repo: "{{item}}"
    state: absent
  with_items:
  - "deb http://http.debian.net/debian {{ansible_distribution_release}}-backports main"
  - "deb https://apt.dockerproject.org/repo debian-{{ansible_distribution_release}} main"
  when: ansible_distribution == "Debian" and
          (ansible_distribution_release == "jessie" or ansible_distribution_release == "wheezy")
  tags: [docker]

- name: remove docker and python-pip on debian
  apt: 
    name: "{{item}}"
    state: absent
  with_items:
  - docker-engine
  - python-pip
  when: ansible_distribution == "Debian" and
          (ansible_distribution_release == "jessie" or ansible_distribution_release == "wheezy")
  tags: [docker]

- name: remove repo key for debian
  apt_key: 
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: absent
  when: ansible_distribution == "Debian" and
          (ansible_distribution_release == "jessie" or ansible_distribution_release == "wheezy")
  tags: [docker]
