---
# handlers file for gitblit
- name: stop gitblit container
  docker:
    name: hub_gitblit_1
    image: "polymont/gitblit"
    state: stopped
    ports:
    - "127.0.0.1:8080:8080"
    - "9418:9418"
    - "29418:29418"
  notify: restart gitblit container

- name: check or build gitblit image
  docker_image: 
    path: "{{gitblit_dir}}"
    name: "polymont/gitblit" 
    state: build

- name: restart gitblit container
  docker:
    name: hub_gitblit_1
    image: "polymont/gitblit"
    state: restarted
    ports:
    - "127.0.0.1:8080:8080"
    - "9418:9418"
    - "29418:29418"
  notify: restart nginx container

- name: test
  shell: 'echo hello' 
