---
# master playbook for Devops platform
- hosts: docker-machines

  roles:
#	get handlers for docker images construction and manipulating containers
   - {role: common}
#	initialize common directories and configuration files
   - {role: init}
#	initialize the base Docker image for all images of the platform (includes SSH capabilities)
   - {role: ubuntu}
#	initialize the base Docker image for Java
   - {role: java}
#	initialize the base Docker image for Tomcat
   - {role: tomcat}
#  deploy ansible
   - {role: ansible}
#  deploy remote (command proxy for scripting from one place across the platform)
   - {role: remote}
   #  deploy jenkins
   - {role: jenkins}
#  deploy gitblit
   - {role: gitblit}
#  deploy registry
   - {role: registry}
#  deploy nginx (reverse proxy for entrypoint unification)
   - {role: nginx}
#  start the last role, performing post-install cleanup operations
   - {role: last}

# temporary add platform host in docker containers
- hosts: docker-machines
  tasks:

  - name: add platform host to docker containers
    command: docker exec {{item}} sh -c 'echo {{ansible_default_ipv4.address}} {{inventory_hostname}}>> /etc/hosts'
    with_items:
    - remote
    - jenkins

  - name: include server file
    include_vars: "/tmp/servers.yml"

  - name: add servers host to ansible containers
    command: docker exec ansible sh -c 'echo {{item.address}} {{item.hostname}}>> /etc/hosts'
    with_items: "{{servers}}"
