# execute: ansible-playbook install_platforme.yml
- hosts: install-machines

  roles:
    - {role: install}
    - {role: docker}
    - {role: ssl}

  tasks:
  - name: remove ssh deployer key to root
    authorized_key: 
      user: root 
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      state: absent
    tags: [install, ssh-remove]
  
# temporary references ip adress and hostname
  - name: create server file in local
    local_action: shell echo 'servers:' > /tmp/servers.yml
    when: inventory_hostname == host_fqdn

  - name: add server info in server file
    local_action: shell echo '- { address':' "{{ansible_default_ipv4.address}}", hostname':' "{{inventory_hostname}}" }' >> /tmp/servers.yml
